Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/0d03e4b2-48cc-4c29-9654-141f96c2d42b/71674600-9d53-4fe9-802d-e698042ea185
Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/bbb87677-da27-468d-910a-f695e9926886/997b04c2-eff4-49f8-b89a-0135e4e4ff82
Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/41292dea-08ea-4e94-a250-9fe83977f2e5/27a9737a-dc0f-4ba7-b4fe-08269f68a879
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/cluster/redirect_logs.py", line 13, in redirect_logs
    yield
  File "/app/cluster/ghap/submit_jobs.py", line 230, in submit_job
    run_ghap_job(job)
  File "/app/cluster/ghap/submit_jobs.py", line 219, in run_ghap_job
    output = upload_to_ghap(c, job, username, password)
  File "/app/.heroku/python/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/app/cluster/ghap/submit_jobs.py", line 193, in upload_to_ghap
    c.put(tar_fullpath, remote=temp_base_dir)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 767, in put
    return Transfer(self).put(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 212, in put
    elif self.is_remote_dir(remote):
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 37, in is_remote_dir
    return stat.S_ISDIR(self.sftp.stat(path).st_mode)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 33, in sftp
    return self.connection.sftp()
  File "<decorator-gen-5>", line 2, in sftp
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 615, in open
    self.client.connect(**kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner


