Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/0a4dcd85-1162-44db-8ccb-87bf5cd44d28/21bdd380-3792-4fec-8ab0-e0b1b02ed4b6
Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/f6a3d4df-bdc1-4b96-bb22-3fb3ad61e57b/cbe4cb45-7c16-4d93-a69f-9468a1f9edee
Command to run:
Rscript --default-packages=methods,stats,utils runner.R script.Rmd inputs.json /tmp/5ef0fa4c-00e3-458b-ab72-788831a91818/8d22034a-5407-410a-8332-8dd570d3ce95
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/cluster/redirect_logs.py", line 13, in redirect_logs
    yield
  File "/app/cluster/ghap/submit_jobs.py", line 230, in submit_job
    run_ghap_job(job)
  File "/app/cluster/ghap/submit_jobs.py", line 219, in run_ghap_job
    output = upload_to_ghap(c, job, username, password)
  File "/app/.heroku/python/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/app/cluster/ghap/submit_jobs.py", line 193, in upload_to_ghap
    c.put(tar_fullpath, remote=temp_base_dir)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 767, in put
    return Transfer(self).put(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 212, in put
    elif self.is_remote_dir(remote):
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 37, in is_remote_dir
    return stat.S_ISDIR(self.sftp.stat(path).st_mode)
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/transfer.py", line 33, in sftp
    return self.connection.sftp()
  File "<decorator-gen-5>", line 2, in sftp
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/app/.heroku/python/lib/python3.6/site-packages/fabric/connection.py", line 615, in open
    self.client.connect(**kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/app/.heroku/python/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner


